---
- name: Add multiline configuration to Cisco IOS XR device
  hosts: all
  gather_facts: no
  tasks:
    - name: Configure multiline settings
      cisco.iosxr.iosxr_config:
        lines:
          - "interface GigabitEthernet0/0/0/1"
          - " description Configured by Ansible with multiline config"
          - " no shutdown"
          - " ip address 192.168.3.1 255.255.255.0"
          - "interface GigabitEthernet0/0/0/2"
          - " description Another interface configured by Ansible"
          - " no shutdown"
          - " ip address 192.168.4.1 255.255.255.0"
