---
- name: Configure Cisco IOS XR device
  hosts: all
  gather_facts: no
  tasks:
    - name: Configure interface GigabitEthernet0/0/0/0
      cisco.iosxr.iosxr_interface:
        name: GigabitEthernet0/0/0/0
        description: Configured by Ansible
        enabled: true
        ipv4:
          address: 10.0.0.2
          mask: 24

    - name: Set hostname
      cisco.iosxr.iosxr_system:
        hostname: Mohan_testing

    - name: Configure NTP server
      cisco.iosxr.iosxr_ntp:
        config:
          - server: 10.0.0.1

    - name: Configure SNMP
      cisco.iosxr.iosxr_snmp:
        config:
          - community: public
            access_list: 10
            readonly: true
